name: Build with Maven and Merge Conflicts

on:
  push:
    branches:
      - '*'

jobs:
  maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Output state
        run: |
          pwd
          ls
          env | sort
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify  

  merge-conflict-check:
    runs-on: ubuntu-latest
    needs: maven
    steps:
      - uses: actions/checkout@v2
      - name: Check for merge conflicts
        run: |
          git fetch
          conflicts=$(git diff origin/${{ github.head_ref }}...${{ github.ref }} --name-only --diff-filter=U)
          if [ -n "$conflicts" ]; then
            echo "Merge conflicts detected!"
            echo "$conflicts" > merge_conflicts.txt
            exit 1
          fi


      - name: Merge changes with parent branch
        if: steps.check-for-merge-conflicts.outcome != 'failure'
        env:
          PARENT_BRANCH: ${{ github.head_ref }}
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_EMAIL}"
          git checkout $PARENT_BRANCH
          git merge --no-ff --no-edit HEAD
          git push origin $PARENT_BRANCH



