name: Build with maven test

on:
  push:
    branches:
      - ${{ github.ref }}

jobs:
 
  maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Output state
        run: |
          pwd
          ls
          env | sort
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify  
       
  check-merge-conflict:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check for merge conflicts
        run: |
          git fetch origin ${{ github.ref }}
          git diff --name-only HEAD...origin/${{ github.ref }} | xargs git checkout --no-progress --
          git merge --no-commit --no-ff origin/${{ github.ref }}
          if git diff --cached --name-only | grep -q .; then
            git merge --abort
            echo "Merge conflict found. Aborting merge."
            exit 1
          fi

  merge-on-push:
    runs-on: ubuntu-latest
    needs: check-merge-conflict
    if: ${{ needs.check-merge-conflict.result == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Git CLI
        uses: GitHubCLI/setup-gh@v1
        with:
          gh_version: 2.2.1
      - name: Merge pull request
        run: |
          gh pr merge --auto --merge
          echo "Merged successfully."

