name: Build with Maven and Merge Conflicts

on:
  push:
    branches:
      - '*USERSTORY*'

jobs:
  maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Output state
        run: |
          pwd
          ls
          env | sort
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify

  merge-conflict-check:
    runs-on: ubuntu-latest
    needs: maven
    steps:
      - uses: actions/checkout@v2
      - name: Check for merge conflicts
        run: |
          git fetch
          conflicts=$(git diff origin/${{ github.head_ref }}...${{ github.ref }} --name-only --diff-filter=U)
          if [ -n "$conflicts" ]; then
            echo "Merge conflicts detected!"
            echo "$conflicts" > merge_conflicts.txt
            exit 1
          else
            git merge "${{ github.ref }}"
          fi




