name: Build with Maven and merge on push

on:
  push:
    branches:
      - '*'

jobs:
  maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Output state
        run: |
          pwd
          ls
          env | sort
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
   
  merge-check:
    runs-on: ubuntu-latest
    needs: maven
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Merge issue branch into current branch
        run: |
          git merge --no-commit --no-ff ${{ github.event.ref }}

      - name: Check for merge conflicts
        run: |
          if [[ -n $(git diff --name-only --diff-filter=U) ]]; then
            echo "There is a merge conflict, please resolve it before merging"
            git merge --abort
            exit 1
          else
            echo "No merge conflicts"
          fi 



