name: Check for merge confict for issues

on:
  push:
    branches:
      - 'issue/*'

jobs:
  merge-conflict-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Check for merge conflicts
        run: |
          git merge --no-commit --no-ff HEAD^
          if [ -n "$(git diff --name-only --diff-filter=U)" ]; then
            echo "Merge conflicts detected, please resolve before merging"
            exit 1
          fi
